### ISSUE TITLE
Descargable de Histórico de cursos y capacitados

### ISSUE THREAD

**Issue by csanhueza2** [mutual-capacitacion/sacc-issues#12]
Estimados:

Se requiere incorporar un histórico descargable masivo de cursos y capacitados considerando los siguientes ítem en formato excel:

-Nombre curso y código
-Nombre relator
-Fecha de inicio y Fecha de término
-Rut  y nombre empresa que inscribe
-Tipo de documento de pago
-N° de orden de compra o transferencia utilizada
-N° de factura asociada
- Nombre y rut del trabajador inscrito
-Estado del participante (aprobado o reprobado)

Gracias

Lo anterior para responder de manera expedita a requerimientos de empresas por cursos y trabajadores capacitados según orden de compra utilizada.

**Comment by chapalele** [comment]
Gracias Cristian por el comentario, la característica se agregó sin observaciones al plan de trabajo.
Mientras tanto, esa información está disponible al hacer clic en una empresa y ver la lista de "inscripciones", donde aparecen todas las "compras" asociadas a una empresa.
