### ISSUE TITLE
Incorporar el rol del Usuario SACC 2

### ISSUE THREAD

**Issue by csanhueza2** [mutual-capacitacion/sacc-issues#13]
Estimados:

Junto con saludar, solicito considerar incorporar el rol del usuario dentro del pool de caracteres visibles al momento de usar el buscador como administrador. Así se podrá diferenciar si es usuario administrador, participante o facilitador

Gracias.

**Comment by chapalele** [comment]
Gracias @csanhueza2 ,
quedó disponible en la lista general de usuarios y en la lista de usuarios de la empresa
