### ISSUE TITLE
Incorporar "Registrar Usuario " en la Portada

### ISSUE THREAD

**Issue by csanhueza2** [mutual-capacitacion/sacc-issues#14]
Estimados:

Junto con saludar, solicito considerar incorporar en la portada de SACC 2 el ítem registrar usuario, con el fin de entregar la responsabilidad de registro a la misma empresa y disminuir el flujo de contactos telefónicos por este tema, por su parte el administrador mutual sólo tendría que validar la solicitud.

Por lo anterior, también debe desarrollarse un item para el administrador que haga referencia a validar inscripciones de nuevos usuarios.

Gracias.

**Comment by chapalele** [comment]
La creación abierta de usuarios en el sitio estará disponible en la próxima publicación.

**Comment by chapalele** [comment]
¿cómo deben validarse las altas de usuario? ¿qué es lo que se valida?
preguntas para la reunión semanal
