### ISSUE TITLE
Código Empresa Automático

### ISSUE THREAD

**Issue by csanhueza2** [mutual-capacitacion/sacc-issues#15]
Estimados.

Junto con saludar, se solicita considerar en el ítem creación nueva empresa que el código mutual sea un valor automático caso contrario retrasa la gestión de inscripción tanto para una empresa que creará un usuario o el coordinador. 

Gracias

**Comment by chapalele** [comment]
Gracias por el comentario, vamos a recuperar los criterios para generar ese código mutual y será incorporado al sistema

**Comment by chapalele** [comment]
confirmar en reunión semanal cómo se genera ese código

**Comment by chapalele** [comment]
el código mutual (o número de adherente) no puede ser generado por este sistema, es un valor que viene dado por el número de contrato de la empresa con mutual.
Por el momento, sacc no puede obtener programáticamente ese valor.
