### ISSUE TITLE
Incorporar Item a "Sedes"

### ISSUE THREAD

**Issue by csanhueza2** [mutual-capacitacion/sacc-issues#16]
Estimados:

Junto con saludar, por favor considerar incorporar en el detalle de creación de sedes:

-Encargado Sede.
-Telefono de contacto
-Aforo 
-Jornada disponible AM y PM

Lo anterior para agilizar el contacto y elección de sedes para cursos en terreno por parte de coordinadores.

Graicas

**Comment by chapalele** [comment]
Gracias @csanhueza2 por el comentario
Los cambios están disponibles en la última actualización.
