### ISSUE TITLE
Incorporar términos y condiciones a inscripciones

### ISSUE THREAD

**Issue by csanhueza2** [mutual-capacitacion/sacc-issues#19]
Estimados:

Junto con saludar, por favor considerar para el proceso de inscripción de participantes, perfil usuario empresa, un ítem en el cual el cliente declare estar de acuerdo con los términos y condiciones del servicio a solicitar y que esto último, esté linkeado a un detalle de las condiciones de entrega del servicio, con el fin de que se respeten y cumplan los protocolos del servicio.

Gracias

**Comment by chapalele** [comment]
Necesitamos conseguir esos términos de uso para publicarlos

**Comment by chapalele** [comment]
TÉRMINOS Y CONDICIONES
--
 
La inscripción en los cursos de Mutual Capacitación está sujeta a los términos y condiciones que se indican más adelante.
La persona que inscribe, en representación de su Empresa, declara que conoce y acepta estos términos y condiciones.
• Los cursos tienen un mínimo de 25 participantes y un máximo de 30. (Cursos cerrados o abiertos). De no llenar los cupos necesarios, Mutual Capacitación puede cancelar el curso, avisando a las empresas que hayan inscrito participantes.
• Es responsabilidad de cada empresa que trabaje con OTIC, inscribir el curso a través de ésta y realizar los trámites de inscripción en SENCE.
• Para la aprobación del curso, se exige un 100% de asistencia y puntualidad. De lo contrario el participante está expuesto a ser reprobado por inasistencia.
• La inscripción en cursos debe ser documentada mediante una Orden de Compra, emitida a nombre de Mutual de Seguridad Capacitación S.A., Rut 76.410.180-4 y debe ser adjuntada en forma electrónica a la inscripción hecha mediante el sistema en Internet.
• Alternativamente a una Orden de Compra, la inscripción puede pagarse por adelantado. El comprobante de pago debe adjuntarse en forma electrónica a la inscripción hecha mediante el sistema en Internet.
• El pago se debe hacer mediante deposito en la Cuenta Corriente N°. 10675612 del Banco BCI, o bien mediante una transferencia bancaria.
• Las empresas tienen hasta 8 horas hábiles antes de que comience el curso para solicitar la anulación o modificación de la nómina de participantes se debe realizar a través de correo electrónico al coordinador respectivo. Pasado ese plazo, se entenderá que los participantes están confirmados y procederá al cobro de todos los inscritos.
• Los participantes deben presentarse con su cedula de identidad. De lo contrario no podrán ingresar al curso.
• Los participantes podrán reprobar el curso de capacitación por los siguientes motivos:      - El uso de CELULARES dentro y fuera de la sala de clases mientras se imparte el curso.      - Ser sorprendido hablando por Celular en los PASILLOS del establecimiento, sin autorización.      - Salir del establecimiento sin autorización de la Coordinación.      - No respetar los horarios del curso 8:30 a 13:00 y 14:30 a 18:00.      - Tomarse más del tiempo permitido para los BREAK (20 min).      - La no participación y disposición al curso y sus actividades.
• Es responsabilidad de cada empresa informar a su trabajador que se encuentra haciendo uso de la franquicia SENCE, por lo cual se requiere de manera obligatoria que el trabajador firme el libro electrónico con su huella digital, de lo contrario Mutual Capacitación no se hace responsable de la perdida de la franquicia y el costo del curso pasara directamente a la empresa solicitante de la inducción.
• Al término del curso se emitirán los certificados correspondientes.
• Las facturas serán enviadas a los domicilios de las Empresas, registrado en el sistema.

**Comment by csanhueza2** [comment]
Estimado Danilo:

Junto con saludar, entrego los términos y condiciones de Masso, al revisar los enviados, éstos difieren a los vigentes del proyecto diversos- Masso:


La inscripción en los cursos de Mutual Capacitación está sujeta a los términos y condiciones que se indican a continuación.

La persona que inscribe, en representación de su Empresa, declara que conoce y acepta estos términos y condiciones.

Capacidad de asistentes en curso:

• Los cursos tienen un mínimo de 25 participantes y un máximo de 40 para cursos presenciales con franquicia tributaria, para cursos streaming con franquicia tributaria el máximo de participantes será de 20 personas.

• Los cursos virtuales Inducción Industrial SSO Arauco tendrán un máximo de cupo de 15 participantes, y un mínimo operacional de 10 participantes.

Requisitos de inscripción y participación:

• El trabajador que participara de las capacitaciones debe ser mayor de 18 años, saber leer y escribir. Podrá existir excepción para aquellos cursos que por su finalidad busquen cubrir las brechas indicadas en este punto.

• No se permitirá el ingreso de personas a los cursos si éstos no han sido previamente inscritos y Mutual Capacitación haya autorizado y validado la inscripción.

• Para los cursos con franquicia tributaria es responsabilidad de cada empresa que trabaje con OTIC, inscribir el curso a través de ésta y realizar los trámites de inscripción en SENCE.

• Para la aprobación del curso, se exige un 100% de asistencia y 100% en las evaluaciones. de no cumplir el requisito de aprobación el participante será reprobado.

• Para realizar la inscripción, la empresa deberá documentar mediante una Orden de Compra, emitida a nombre de Mutual de Seguridad Capacitación S.A. esta orden de compra debe ser adjuntada en forma electrónica y en formato PDF a la inscripción. Las empresas también podrán cancelar por medio de transferencia electrónica o depósito bancario, este comprobante de pago deberá adjuntarse en formato PDF a la inscripción. El pago se debe hacer mediante depósito en la Cuenta Corriente N°. 10675612 del Banco BCI, o bien mediante una transferencia bancaria.

• La empresa una vez realizada la inscripción al curso, podrán anular o modificar la nómina de participantes, siempre que el aviso sea emitido y recepcionado por el área de coordinación 24 horas previas al comienzo del curso. Pasado ese plazo, se entenderá que los participantes están confirmados y procederá al cobro de todos los inscritos.

• Una vez confirmado y validado los documentos de inscripción, el área de coordinación procederá a aprobar la inscripción enviándole un correo de respaldo a la empresa, para este caso se enviará al correo del encargado de realizar inscripciones por parte de la empresa (correo utilizado como ID usuario al ingresar a este portal y registrado en perfil de empresa) • En el correo de aprobación de inscripción se enviará la dirección de ejecución del curso y o el link de acceso para la conexión vía streaming, es responsabilidad de la empresa disponibilizar o entregar a cada trabajador el link de acceso de la inscripción para cursos virtuales. Si el trabajador no se conecta al curso el cobro de su participación se hará efectiva.

• Los participantes deben presentarse con su cedula de identidad para cursos presenciales y disponibilizar su c.i. en curso virtuales, para este último el coordinador podrá solicitar visualizar el documento. De lo contrario no podrán participar en el curso.

• Es responsabilidad de cada empresa, informar al trabajador que su participación se encuentra haciendo uso de la franquicia SENCE, por lo cual se requiere de manera obligatoria que el trabajador firme el libro electrónico con su huella digital, de lo contrario Mutual Capacitación no se hace responsable de la perdida de la franquicia y el costo del curso pasara directamente a la empresa solicitante de la inducción.

• Una vez finalizado el curso, los certificados de aprobación estarán disponibles a las 24 siguientes

• Las facturas serán enviadas de forma digital a las casillas de las Empresas disponibilizada en S.I.I.


Saludos Cordiales,


Cristian Sanhueza Riveros

Coordinador Proyectos Capacitaciones Zonal Bío Bío/Ñuble

Mutual Asesorías y Capacitación

Fono: (56) 41 2727393

Dirección: Avda. Autopista 8696 Of. 508, Hualpén-Concepción

[cid:b5be5e19-077f-468a-a7bc-e38756762a13]
________________________________
De: Danilo Lizama <notifications@github.com>
Enviado: lunes, 1 de marzo de 2021 8:54
Para: mutual-capacitacion/sacc-issues <sacc-issues@noreply.github.com>
Cc: Cristian Rodrigo Sanhueza Riveros <csanhueza@masesorias.cl>; Author <author@noreply.github.com>
Asunto: Re: [mutual-capacitacion/sacc-issues] Incorporar términos y condiciones a inscripciones (#19)


TÉRMINOS Y CONDICIONES


La inscripción en los cursos de Mutual Capacitación está sujeta a los términos y condiciones que se indican más adelante.
La persona que inscribe, en representación de su Empresa, declara que conoce y acepta estos términos y condiciones.
• Los cursos tienen un mínimo de 25 participantes y un máximo de 30. (Cursos cerrados o abiertos). De no llenar los cupos necesarios, Mutual Capacitación puede cancelar el curso, avisando a las empresas que hayan inscrito participantes.
• Es responsabilidad de cada empresa que trabaje con OTIC, inscribir el curso a través de ésta y realizar los trámites de inscripción en SENCE.
• Para la aprobación del curso, se exige un 100% de asistencia y puntualidad. De lo contrario el participante está expuesto a ser reprobado por inasistencia.
• La inscripción en cursos debe ser documentada mediante una Orden de Compra, emitida a nombre de Mutual de Seguridad Capacitación S.A., Rut 76.410.180-4 y debe ser adjuntada en forma electrónica a la inscripción hecha mediante el sistema en Internet.
• Alternativamente a una Orden de Compra, la inscripción puede pagarse por adelantado. El comprobante de pago debe adjuntarse en forma electrónica a la inscripción hecha mediante el sistema en Internet.
• El pago se debe hacer mediante deposito en la Cuenta Corriente N°. 10675612 del Banco BCI, o bien mediante una transferencia bancaria.
• Las empresas tienen hasta 8 horas hábiles antes de que comience el curso para solicitar la anulación o modificación de la nómina de participantes se debe realizar a través de correo electrónico al coordinador respectivo. Pasado ese plazo, se entenderá que los participantes están confirmados y procederá al cobro de todos los inscritos.
• Los participantes deben presentarse con su cedula de identidad. De lo contrario no podrán ingresar al curso.
• Los participantes podrán reprobar el curso de capacitación por los siguientes motivos:      - El uso de CELULARES dentro y fuera de la sala de clases mientras se imparte el curso.      - Ser sorprendido hablando por Celular en los PASILLOS del establecimiento, sin autorización.      - Salir del establecimiento sin autorización de la Coordinación.      - No respetar los horarios del curso 8:30 a 13:00 y 14:30 a 18:00.      - Tomarse más del tiempo permitido para los BREAK (20 min).      - La no participación y disposición al curso y sus actividades.
• Es responsabilidad de cada empresa informar a su trabajador que se encuentra haciendo uso de la franquicia SENCE, por lo cual se requiere de manera obligatoria que el trabajador firme el libro electrónico con su huella digital, de lo contrario Mutual Capacitación no se hace responsable de la perdida de la franquicia y el costo del curso pasara directamente a la empresa solicitante de la inducción.
• Al término del curso se emitirán los certificados correspondientes.
• Las facturas serán enviadas a los domicilios de las Empresas, registrado en el sistema.
