### ISSUE TITLE
Incorporar Bandeja de validación de inscripciones

### ISSUE THREAD

**Issue by csanhueza2** [mutual-capacitacion/sacc-issues#20]
Estimados:

Junto con saludar, por medio del presente solicitamos por favor considerar una bandeja de validación de solicitudes de inscripción, actualmente para acceder a cursos de Proyecto Masso en Sacc 1, se requiere validar con el área de cobranzas la orden de compra o transferencia correspondiente entregada por la empresa antes de concretar la inscripción, una vez validado el pago y que los datos ingresados la empresa recibe un correo de que la inscripción ha sido autorizada.

Sin este control las empresas podrían adjuntar erróneamente documentos en la inscripción y generar contratiempos contables y de facturación.

Gracias

**Comment by chapalele** [comment]
Vamos a validar las funciones actuales del perfil finanzas para incorporar ese rol en esta versión del sistema

**Comment by chapalele** [comment]
En la inscripción había un campo que cambiaba el estado del pago, que fue eliminado por solicitud de la contraparte en mutual.  
Este campo es candidato a volver y ser controlado por el perfil "finanzas"

**Comment by chapalele** [comment]
@csanhueza2 muchas gracias, creo que la lista de inscripciones tiene la característica que buscas

https://sacc.mcap.cl/inscripcion/

con todo, la validación por parte de finanzas será abordada en un proyecto futuro
