### ISSUE TITLE
CAMPOS OBLIGATORIOS EN CREACION DE EMPRESAS Y USUARIOS

### ISSUE THREAD

**Issue by kcofre** [mutual-capacitacion/sacc-issues#21]
Estimados, buenas tardes:
Favor su apoyo, me percate que en SACC2 al momento de realizar la creación de un perfil empresa o de usuario, no esta como campo obligatorio el teléfono de contacto, lo cual es primordial para nosotros para poder comunicarnos tanto con la empresa como del contacto de coordinación o como lo indica el sistema el contacto con el ROL Administración empresa.

Envío imagen en donde cree empres y usuario sin este cambo rellenado

![image](https://user-images.githubusercontent.com/79479067/108764612-9941b680-7531-11eb-9788-361a8fc8e78c.png)

![image](https://user-images.githubusercontent.com/79479067/108764400-4f58d080-7531-11eb-8fae-8f4538abc83a.png)

**Comment by chapalele** [comment]
Gracias @kcofre 

No podemos poner esa restricción, ya que no todos nuestros usuarios tienen un teléfono.

Alternativamente, prodríamos validar que aquellos que tengan rol "administrador empresa" tengan un teléfono inscrito, pero 
eso no valida la calidad de la información, ya que **no tenemos la tecnología para validar que el teléfono sea el correcto**.

Por otra parte, el sistema permite la creación de empresas aún cuando no haya un usuario declarado administrador, esto es  necesario para guardar la compatibilidad con datos históricos.

Este requerimiento parece ser más propio de la gestión del sistema que de su estructura en programación.
