### ISSUE TITLE
IDENTIFICACION USUARIO ADMINITRADOR DE EMPRESA

### ISSUE THREAD

**Issue by kcofre** [mutual-capacitacion/sacc-issues#22]
Estimados, buenas tardes:
Favor su apoyo, me percate que al momento de crear varios usuarios para una empresa, no hay forma de identificar de manera rápido al que posee un Rol de Administración empresa o contacto de coordinación, hay alguna opción de que este salga de manera rápida al momento de explorar los datos de la empresa.

Envió detalle de como esto se puede ver de manera rápida en SACC1

Buscamos a la empresa
![image](https://user-images.githubusercontent.com/79479067/108765707-e40ffe00-7532-11eb-9937-92dd5a685bed.png)

Luego al desplegar la información podemos ver al contacto de coordinación (datos de la persona que suele inscribir cursos)  y el contacto de contabilidad (por lo general quien se encarga de los pagos)

![image](https://user-images.githubusercontent.com/79479067/108765894-29ccc680-7533-11eb-8a1e-b2fdf2be51ab.png)

Quedo atenta a sus comentarios.

Karen Cofré Ojeda
Coordinadora de Capacitación Zona Norte
Fono: (55) 2 651285
Cel: +569 31790442

**Comment by chapalele** [comment]
Gracias @kcofre 
La característica quedó disponible en disponible en la lista general de usuarios y también en la lista de usuarios de la empresa.  Para los requerido, probablemente resulte más útil en esta última.
Tema abordado en #13
