### ISSUE TITLE
Nueva Categoría en programacion 

### ISSUE THREAD

**Issue by kcofre** [mutual-capacitacion/sacc-issues#23]
Estimados, buenas tardes:
Favor su apoyo creando nuevas categorías al momento de crear un programa.

Proyecto Minero - Inducción
Proyecto Minero - Curso específico

![image](https://user-images.githubusercontent.com/79479067/108768081-ffc8d380-7535-11eb-8671-f3db06fd4644.png)

**Comment by chapalele** [comment]
Gracias @kcofre 
Las categorías fueron creadas en la base de datos del sistema
