### ISSUE TITLE
Creación de Nombre de curso automático

### ISSUE THREAD

**Issue by kcofre** [mutual-capacitacion/sacc-issues#24]
Estimados, buenas tardes:
Se puede crear una forma en la cual se pueda generar el nombre de un curso o inducción de manera automática en plataforma sin necesidad de que la escribirlo de manera manual, esto con el fin de evitar errores.

En la plataforma norte.otecmutua.cl el nombre se genera de manera automática el nombre de la inducción o curso al momento de selección el código del curso, y luego agrega las características particulares del mismo como Fecha de inducción y la sede en la cual se ejecutara para diferenciarlos de otros. 
 
![image](https://user-images.githubusercontent.com/79479067/108770224-d0679600-7538-11eb-9bcc-1ac7c4b22357.png)

![image](https://user-images.githubusercontent.com/79479067/108770532-2b998880-7539-11eb-9e49-03ef840313b1.png)

Atenta a sus comentario 

Karen Cofré Ojeda
Coordinadora de Capacitación Zona Norte
Mutual Asesorías y Capacitación
Fono: (55) 2 651285
Cel: +569 31790442

**Comment by chapalele** [comment]
Gracias Karen por el comentario.
En el caso descrito, vemos que se usa lo que sería el equivalente al código del programa para generar el nombre del curso.  Estamos buscando un registro en el cual basarnos para generar el nombre, porque al momento de crear el curso, no tenemos otra información que el nombre del programa a ejecutar.

**Comment by chapalele** [comment]
A fin de implementar la característica, se agregó un botón a la interfaz para "generar" un nombre a partir del programa elegido, la sede y la fecha de inicio.
