### ISSUE TITLE
Definición de Proceso Base de Operación

### ISSUE THREAD

**Issue by SaccVero** [mutual-capacitacion/sacc-issues#26]
Hola Danilo :

 A continuacion te dejaré algunas sugerencias para la visialización con el perfil del coordinador para el ingreso en sacc 2, considerando como base lo que esta en el sacc 1.

Considerando que la plataforma será una sola, esta ya no deberá tener distinción de ingreso por la web por zona (centro.otec – norte.otec -sur.otec).  Al ingresar independiente de la zona del coordinador deberán poder seleccionar el proyecto en el cual operan  y cada usuario tendrá acceso según proyectos.

•	Minería
•	Salud
•	Museg
•	Clientes Diversos

Estos deberían ser los 4 proyectos principales y sobre estos cargar la información correspondiente al proyecto. (algo así como la foto al ingresar pero con los nombres correspondientes)

 

![image](https://user-images.githubusercontent.com/78745250/109713928-9291ef80-7b80-11eb-9023-a806e4fea921.png)

**Comment by chapalele** [comment]
los proyectos fueron sustituidos por categorías

**Comment by chapalele** [comment]
se cierra por el momento, las categorías pueden aceptar más atributos.
