### ISSUE TITLE
Mejoras Para el informe Comercial 

### ISSUE THREAD

**Issue by SaccVero** [mutual-capacitacion/sacc-issues#27]
Para la reportabilidad de todos los proyectos, se considera como base el informe comercial que actualmente se descarga de la zona centro, sin embargo sobre ese es necesario  realizar modificaciones. Este nuevo formato de informen se debe aplicar a todos los proyectos.

Según lo ya mencionado y considerando los campos que aparecen en el informe comercial de actual centro.otec:

•	Agregar una columna para indicar modalidad presencial o virtual 
•	Agregar el columna Monitor en sala , para reflejar el costo asociado
•	El nombre del coordiandor que genera el ID debe ser obligatorio en el informe
•	Sacar las columnas  asistencia relator y dispositivo
•	Las columas sede y sede curso son iguales, solo una columna con direccion fisica
•	Al seleccionar el centro de costo del proyecto, este debe indicar en la columna proyecto en nombre del proyecto al cual corresponde el centro de costo ingresado
•	Columna PGP Actualizar codigos de cursos
•	Los códigos de cursos deben ser creados por jefatura, tener una estandarización y evitar duplicidad.
•	La jefatura debe tener la opcion de abrir y cerrar los cursos para correcciones en caso de error.

![image](https://user-images.githubusercontent.com/78745250/109714515-45fae400-7b81-11eb-9598-3940a03e8fc7.png)

•	Estado de curso: es necesario saber que pasa con el curso una vez que es programado, por  lo tanto se deben ampliar los estados  y se deben justificar las cancelaciones

![image](https://user-images.githubusercontent.com/78745250/109714596-58751d80-7b81-11eb-9415-103dafa1b0f6.png)

•	La descarga del infome comercial, se deberá poder realizar tanto por proyecto y/o zona , pudiendo seleccionar más de un proyecto a la vez.

**Comment by Jorgealday** [comment]
falta Ejecutado dentro de los estados

**Comment by chapalele** [comment]
@Jorgealday @SaccVero 

¿quién tiene derecho a cambiar ese estado? ¿sigue siendo alguno de los administradores de la plataforma?

**Comment by SaccVero** [comment]
@chapalele @Jorgealday 

Estos estados debe ser cambiado por el coordinador del curso (administrador o coordinador), cuando el curso no sea ejecutado de manera efectiva.
El estado ejecutado que menciona @Jorgealday,  corresponde al que se le debe asignar al curso una vez que este evaluado por completo, y se debe asignar de forma automatica al cerrar el curso.

**Comment by chapalele** [comment]
Hay un problema lógico con estos estados: no son exhaustivos y mutuamente excluyentes, mezclan causas con resultados.  en el código se incorporaron todos, pero el problema de diseño persiste. 

Esto es algo que hay que corregir: no deberíamos arrastrar errores de lógica a la nueva versión del sistema.

¿qué es el informe comercial?
