### ISSUE TITLE
Funcionalidades para la vista empresa

### ISSUE THREAD

**Issue by SaccVero** [mutual-capacitacion/sacc-issues#28]
Debe haber un calendario, o una vista similar donde la empresa de manera fácil y rápida pueda elegir ña fecah en la cualparticipara en la capacitación.
•	Mejora en el calendario de programación de cursos, poder seleccionar rango de fechas, hoy se ve todo lo programado (ejemplo vista actual) esto debe aplicar para el perfil empresas y coordinador.

![image](https://user-images.githubusercontent.com/78745250/109715025-df29fa80-7b81-11eb-943e-08221bcf9708.png)

**Comment by chapalele** [comment]
disponible actualmente en la lista de cursos
