### ISSUE TITLE
Funcionalidades en la operacion de la plataforma

### ISSUE THREAD

**Issue by SaccVero** [mutual-capacitacion/sacc-issues#29]
Considerando como base la actual plataforma sacc, lo que se busca dentro de las funcionalidades en el sacc 2 son los siguientes puntos.

•	Para el jefe de proyecto, debe habilitarse una vista rapida de lo programado en un rango de fechas, donde se indique los valores asociados al curso , cupos, fechas, horas para una toma de deciones de forma rápida.
•	Actualmente al derivar al registrar un pago en el portal sur, la empresa carga 10 participantes, generan OC por los 10 y el sistema reporta a facturacion 9 incritos modificando monto a facturar. Esto debe quedar funcional y sin error en la plataforma sacc2, ya que esto genera error en la facturación.(critico)
•	Para el proyecto Museg, es necerario poder hacer cargas masivas de programación (tanto coordinador como JP), para esto es necesario que la informacion que se decargará por excel desde Sigcap, se pueda cargar de forma masiva en la plataforma, registrando el nombre de el experto mutual que realiza el pedido y criticidad del curso (datos se obtienen desde SIGECAP).
•	Para el funcionamiento del segmento de clientes diversos, estaba en proceso la integración del portal Mutual Capacitación (mcap.cl)  con Sacc, ya que actualmente  Sacc es funcional para empresas más no para personas naturales, y la operación de clientes diversos se refleja solo en mcap.cl. Generando riesgos al momento de realizar la facturación, por que el control de esto es de manera manual, aumentando el riesgo de error.
•	El portal Sacc debe enviar alertas para los cursos pendientes de liberación (Inscritos por la empresa), hoy hay una notificación la cual no cumple su objetivo ya que no envía mail a los coordinadores, es solo una burbuja pequeña.

![image](https://user-images.githubusercontent.com/78745250/109715448-6d05e580-7b82-11eb-8dae-9247b2dd0655.png)

**Comment by chapalele** [comment]
HELP!
¿qué es el jefe de proyecto?
¿qué es el portal sur?
¿qué es el proyecto museg?
¿qué es un cliente diverso?
¿qué es un curso pendiente de liberación?
