### ISSUE TITLE
Mejoras en el proceso de facturacion

### ISSUE THREAD

**Issue by SaccVero** [mutual-capacitacion/sacc-issues#30]
Basado en el Sacc  actual y solo implementando mejoras.

•	Al monento de liberar un curso y enviar a facturar, el coordinador debe autorizar con un chek y/o V°B° e indicar en una casilla si facturacion esta sujeta a HES y un campos de observaciones. Debe condicion este campo antes de que pase a ser facturado, esta revisión ser vible para el facturador.
•	Para el proceso de facturación de Clentes diversos, este es llevado por fuera de la plataforma, no hay un proceso de facturación masiva, incrementando el rago de error al hacer esta tarea manual. Es por eso que se pide integracion entre mcap.cl y Sacc.

**Comment by chapalele** [comment]
Tenemos que revisar en qué consiste el proceso de facturación.  No tenemos documentación ni mandato sobre este punto.  La facturación se hace desde el sistema contable.
