### ISSUE TITLE
incorporar código sencenet en carga masiva de participantes a cursos

### ISSUE THREAD

**Issue by Jorgealday** [mutual-capacitacion/sacc-issues#33]
incorporar código sencenet a la carga masiva de participantes, puede haber más de un código por curso

**Comment by chapalele** [comment]
@Jorgealday El código sencenet ¿es una propiedad del curso o del estudiante?

**Comment by Jorgealday** [comment]
del estudiante en un curso específico.
este dato viene en la OC entregada por la empresa o la OTIC
