### ISSUE TITLE
incorporar código cdr y código sence

### ISSUE THREAD

**Issue by Jorgealday** [mutual-capacitacion/sacc-issues#34]
incorporar código CDR y código sence en creación de programa.

el código sence debe además tener una fecha fin 

el código CDR debe estar predefinido y estar en un mantenedor

**Comment by chapalele** [comment]
@Jorgealday ¿qué es el código CDR?, ¿debemos crear una nueva entidad?

**Comment by Jorgealday** [comment]
el CDR es un código de responsabilidad, es el centro de costo donde se cargan los proyectos.
ejemplo: 6-05-B34 

¿por qué una nueva entidad?
