### ISSUE TITLE
 Alta, Baja y Actualización de Usuarios

### ISSUE THREAD

**Issue by csanhueza2** [mutual-capacitacion/sacc-issues#36]
1.- Alta, Baja y Actualización de Usuarios: Ingresar con perfil Administrador a la opción Usuarios localizado en el menú superior de la plataforma.
Instrucciones:
•	Ingresar a https://sacc.mcap.cl con los siguientes datos:

•	Dirigirse a la opción Usuarios y presionar en el botón Nuevo ubicado en la parte superior derecha de la pantalla.

•	En la opción Usuarios ingresar los datos de un nuevo usuario, para lo cual debe completar todos los campos marcados con borde de color rojo (Obligatorios) y en los cuales se debe definir el rol que tendrá en sistema, además de definir las categorías y/o etiquetas las restringirán la navegación del usuario en el sistema, posterior a la selección e ingresos de los datos requeridos presionar en Grabar.

•	Una vez registrado el usuario presionar en editar de la columna acciones de la Grilla para modificar el rol y etiquetas del usuario determinado, para luego presionar en Grabar.

OBSERVACIONES:
•	Se procede a crear usuario “Carlos Salas” en SACC 2.
•	No se permite crear usuario con correo ya existente en SACC 2. En la realidad hay trabajadores que no tienen correos electrónicos por el no manejo de plataformas, por lo cual sus jefaturas incorporan su correo personal pero si  este ya está registrado en el portal no se concretará el registro. 

Mejoras:
•	Habilitar la inscripción de personas con correos ya existentes en plataforma.

**Comment by chapalele** [comment]
La dirección de correo no puede ser compartida:
a) forma parte de la identidad del usuario en otras plataformas que interactúan con sacc (moodle, wordpress)
b) para todo tipo de aplicaciones futuras (mobile, sso, etc)

En caso de que se necesite crear un registro sin correo, debe utilizarse una dirección única ficticia.
Debemos determinar con IT cuál será el dominio de esas direcciones ficticias. (ej. @users.mcap.cl)
